version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: bancok
      POSTGRES_USER: bancok_user
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  auth-service:
    build:
      context: ./services/auth
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgresql://bancok_user:${DB_PASSWORD}@postgres:5432/bancok
      JWT_SECRET: ${JWT_SECRET}
      REDIS_URL: redis://redis:6379
    depends_on:
      - postgres
      - redis

volumes:
  pg_data:
  redis_data: